export default defineAppConfig({
  pages: [
    'pages/index/index',
    'pages/login/index',
    'pages/discover/index',
    'pages/messages/index',
    'pages/search-results/index',
    'pages/notification-list/index',
    'pages/contact-request/index',
    'pages/message-likes/index',
    'pages/message-follows/index',
    'pages/message-comments/index',
    'pages/message-system/index',
    'pages/chat/index',
    'pages/profile/index',
    'pages/profile/view',
    'pages/avatar-select/index',
    'pages/edit-profile/index',
    'pages/settings/index',
    'pages/settings-detail/index',
    'pages/edit-skills/index',
    'pages/my-skills/index',
    'pages/my-posts/index',
    'pages/my-followers/index',
    'pages/my-following/index',
    'pages/my-ratings/index',
    'pages/my-activities/index',
    'pages/my-partners/index',
    'pages/my-favorites/index',
    'pages/post-detail/index',
    'pages/post-manage/index',
    'pages/publish/index',
    'pages/activity-register/index',
    'pages/verify/index',
    'pages/skill-detail/index',
    'pages/skill-proof-detail/index',
    'pages/interest-detail/index',
    'pages/user-detail/index',
    'pages/user-skills/index',
    'pages/user-posts/index',
    'pages/user-followers/index',
    'pages/user-following/index',
    'pages/browse-history/index',
  ],
  window: {
    navigationBarTitleText: '换乎ZJU版',
    navigationBarTextStyle: 'black',
    navigationBarBackgroundColor: '#FFFFFF',
    backgroundColor: '#F8FAFC',
    backgroundTextStyle: 'light',
  },
  tabBar: {
    color: '#94A3B8',
    selectedColor: '#2563EB',
    backgroundColor: '#FFFFFF',
    borderStyle: 'black',
    list: [
      {
        pagePath: 'pages/index/index',
        text: '首页',
        iconPath: 'assets/icons/home.png',
        selectedIconPath: 'assets/icons/home-active.png',
      },
      {
        pagePath: 'pages/discover/index',
        text: '发现',
        iconPath: 'assets/icons/discover.png',
        selectedIconPath: 'assets/icons/discover-active.png',
      },
      {
        pagePath: 'pages/messages/index',
        text: '消息',
        iconPath: 'assets/icons/messages.png',
        selectedIconPath: 'assets/icons/messages-active.png',
      },
      {
        pagePath: 'pages/profile/index',
        text: '我的',
        iconPath: 'assets/icons/profile.png',
        selectedIconPath: 'assets/icons/profile-active.png',
      },
    ],
  },
  usingComponents: {},
})
